### PR TITLE
feat: add Platform.isWeb

### LINKED ISSUE #31: Add isWeb
Until https://github.com/flutter/flutter/issues/39998 would it make sense to add `isWeb` as part of this package? 

Related issues

- https://github.com/flutter/flutter/issues/79413

### LINKED ISSUE #556: Add isWeb
Until https://github.com/flutter/flutter/issues/39998 would it make sense to add `isWeb` as part of this package? 

Related issues

- https://github.com/flutter/flutter/issues/79413

### PR DESCRIPTION
**Pull request by felangel**
closes dart-lang/core#556

### CODE REVIEW

**Comment by GroovinChip** [comment]
@kevmoo is this package abandoned? Will this PR get merged?

**Comment by kevmoo** [comment]
I don't know if anyone is maintaining this package any more 🤷

**Comment by mit-mit** [comment]
That's not entirely correct; we're currently investigating how to best evolve this API and a few related APIs.

**Comment by stuartmorgan-g** [comment]
The source for this package has moved to `flutter/packages`; closing.

Since there is not yet agreement on adding this to `platform`, I would suggest starting with a proposal issue in flutter/flutter before re-opening a new PR in flutter/packages.

**Pull request closed without merging**
