### PR TITLE
Update readme: drop broken coverage and CI badges

### PR DESCRIPTION
**Pull request by kevmoo**
Also drop superfluous title

### CODE REVIEW

**Comment by kevmoo** [comment]
@mit-mit – who owns this?

**Comment by mit-mit** [comment]
I usually ping some of the lovely folks from the commit history here: https://github.com/google/platform.dart/commits/master

**Comment by kevmoo** [comment]
@gspencergoog ?

**Comment by gspencergoog** [comment]
Sorry, I was OOO last week. Sure, I can do that.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by kevmoo** [comment]
@gspencergoog – you'll have to merge, too. I lack keys!

**Pull request merged**
